apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: tracking

data:
  MLFLOW_HOST: "0.0.0.0"
  MLFLOW_PORT: "5000"
  MLFLOW_DEFAULT_ARTIFACT_ROOT: "s3://mlflow-artifacts/"
  SETTINGS_PATH: "/app/config/settings.yaml"
  SCORING_DATE: ""
