apiVersion: batch/v1
kind: CronJob
metadata:
  name: training-job
  labels:
    app.kubernetes.io/name: amazon-data-predict
    app.kubernetes.io/component: training
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: amazon-data-predict
            app.kubernetes.io/component: training
        spec:
          restartPolicy: OnFailure
          containers:
            - name: training
              image: ghcr.io/your-org/amazon-data-predict-training:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: SETTINGS_PATH
                  value: /app/config/settings.yaml
              envFrom:
                - configMapRef:
                    name: mlflow-config
                - secretRef:
                    name: mlflow-secrets
                - secretRef:
                    name: app-secrets
              volumeMounts:
                - name: settings
                  mountPath: /app/config
          volumes:
            - name: settings
              configMap:
                name: app-settings
