env: "prod"
timezone: "UTC"
sites:
  - "US"
  - "UK"
  - "DE"
asin_pool_source: "db"
rate_limits:
  unified_api:
    qpm: 200
    burst: 200
    timeout_sec: 10
  keepa:
    qpm: 50
    burst: 50
    timeout_sec: 10
  spapi:
    qpm: 60
    burst: 60
    timeout_sec: 10
  paapi:
    qpm: 20
    burst: 20
    timeout_sec: 10
  helium10:
    qpm: 30
    burst: 30
    timeout_sec: 10
  junglescout:
    qpm: 30
    burst: 30
    timeout_sec: 10
retry_policy:
  max_attempts: 5
  base_delay_ms: 500
  jitter_ms: 300
  max_delay_ms: 60000
windows:
  lookback_days: 28
  horizon_days: 30
storage:
  db:
    driver: "postgresql"
    host: "localhost"
    port: 5432
    user: "asin"
    dbname: "asin_analytics"
  s3_like:
    bucket: "raw-json"
    prefix: "unified_api/"
features:
  rolling:
    - 7
    - 14
    - 30
  min_reviews: 5
scoring:
  model_version: "rank-lgbm"
  model_path: "artifacts/rank/model.txt"
  price_band_column: "price_band"
  identifier_columns:
    - "asin"
    - "site"
    - "dt"
    - "category"
    - "price_band"
  group_by_columns:
    - "site"
    - "category"
    - "price_band"
  weights:
    bsr_trend_30: 0.35
    est_sales_30: 0.25
    review_vel_14: 0.20
    price_vol_30: -0.10
    listing_quality: 0.30
exports:
  views:
    - name: "vw_top_candidates_daily"
      path: "exports/top_candidates"
    - name: "vw_features_latest"
      path: "exports/features_latest"
ai:
  enabled: false
  comment_summary_table: ""
  keyword_cluster_table: ""
  export_path: ""
  provider: "openai"
  providers:
    openai:
      label: "OpenAI"
      api_key_env: "OPENAI_API_KEY"
      api_base_env: "OPENAI_API_BASE"
    qwen:
      label: "Qwen (DashScope)"
      api_key_env: "QWEN_API_KEY"
      api_base_env: "QWEN_API_BASE_URL"
    claude:
      label: "Claude (Anthropic)"
      api_key_env: "CLAUDE_API_KEY"
      api_base_env: "CLAUDE_API_BASE_URL"
logging:
  level: "INFO"
  json: true
  destination: "stdout"
