name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          # 若你的包是可安装的（pyproject.toml / setup.cfg / setup.py），建议可编辑安装：
          if [ -f pyproject.toml ] || [ -f setup.cfg ] || [ -f setup.py ]; then python -m pip install -e .; fi

      - name: Lint with flake8
        run: |
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Show Python & PyTest versions
        run: |
          which python
          python -V
          python -c "import sys; print('py exec:', sys.executable)"
          python -m pytest --version

      - name: Check dataclass(slots) support
        run: |
          python - <<'PY'
          import sys
          from dataclasses import dataclass
          try:
              @dataclass(slots=True)
              class X: a:int=1
              print("dataclass(slots) OK on", sys.version)
          except TypeError as e:
              print("dataclass(slots) FAILED on", sys.version, ":", e)
              raise SystemExit(1)
          PY

      - name: Test with pytest
        run: python -m pytest -q
